export const COUNTRIES: { name: string; flag: string; cities: string[] }[] = [
  {
    name: 'Bénin',
    flag: '🇧🇯',
    cities: [
      'Cotonou',
      'Porto-Novo',
      'Parakou',
      'Abomey-Calavi',
      'Bohicon',
      'Djougou',
      'Natitingou',
      'Ouidah',
      'Lokossa',
      'Abomey',
    ],
  },
  {
    name: 'Togo',
    flag: '🇹🇬',
    cities: [
      'Lomé',
      'Sokodé',
      'Kara',
      'Kpalimé',
      'Atakpamé',
      'Dapaong',
      'Tsévié',
      'Aného',
      'Bassar',
      'Notsé',
    ],
  },
  {
    name: 'Sénégal',
    flag: '🇸🇳',
    cities: [
      'Dakar',
      'Thiès',
      'Touba',
      'Rufisque',
      'Saint-Louis',
      'Mbour',
      'Kaolack',
      'Ziguinchor',
      'Diourbel',
      'Louga',
    ],
  },
  {
    name: "Côte d'Ivoire",
    flag: '🇨🇮',
    cities: [
      'Abidjan',
      'Yamoussoukro',
      'Bouaké',
      'San-Pédro',
      'Korhogo',
      'Daloa',
      'Man',
      'Gagnoa',
      'Divo',
      'Anyama',
    ],
  },
];
